### ISSUE TITLE
由于你的帐号存在异常，需要进行手机验证， 请使用QQ手机版扫码进行登录。 最近一直出这个，请问应该如何解决

### ISSUE THREAD

**Issue by kanxue2002** [stefanJi/BuglyCrashSpider#1]

**Comment by jeniva** [comment]
我的qq也提示账号异常，请问有其他办法能爬到bugly的数据吗
![image](https://user-images.githubusercontent.com/8514029/66751028-9efca600-eec0-11e9-99d5-5df96c4da7aa.png)

**Comment by stefanJi** [comment]
目前暂时没有额，只能通过手机QQ扫码进入下一步了。
